export const GET_PRODUCTLIST_REQUEST = "GET_PRODUCTLIST_REQUEST"; //fire saga
export const PRODUCTLIST_RESPONSE = "PRODUCTLIST_RESPONSE"; //receive list(store response)

//Product Details
export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"; //FIRE SAGA
export const PRODUCT_DETAILS_RESPONSE = " PRODUCT_DETAILS_RESPONSE";
